# Generated by Django 2.1.5 on 2019-06-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190614_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
