# Generated by Django 2.1.5 on 2019-06-16 02:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
