# Generated by Django 2.1.5 on 2019-06-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20190616_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='chatparticipants',
            name='group_members',
        ),
        migrations.RemoveField(
            model_name='chatparticipants',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatParticipants',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
