# Generated by Django 2.1.5 on 2019-07-05 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0010_chat_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='initiator',
            field=models.ForeignKey(default=222, on_delete=django.db.models.deletion.CASCADE, related_name='init', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
