# Generated by Django 2.1.5 on 2019-07-06 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_chat_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
    ]
