# Generated by Django 2.1.5 on 2019-07-10 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0017_auto_20190710_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deleted',
            field=models.ManyToManyField(blank=True, related_name='deleted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
