# Generated by Django 2.1.5 on 2019-07-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_reportchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportchat',
            name='content',
            field=models.TextField(default=225),
            preserve_default=False,
        ),
    ]
