# Generated by Django 2.1.7 on 2019-03-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_saved_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='saved_post',
            new_name='saved',
        ),
    ]
