# Generated by Django 2.1.7 on 2019-03-31 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='follower',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
    ]
