# Generated by Django 2.1.7 on 2019-03-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_follow_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
