# Generated by Django 2.1.7 on 2019-03-31 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
