# Generated by Django 2.1.7 on 2019-04-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='content',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
    ]
