# Generated by Django 2.1.7 on 2019-04-13 07:29

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_share_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
    ]
