# Generated by Django 2.1.7 on 2019-04-14 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20190413_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
