# Generated by Django 2.1.7 on 2019-04-18 15:03

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20190416_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=400, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
