# Generated by Django 2.2 on 2019-04-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_3',
        ),
    ]
