# Generated by Django 2.2 on 2019-04-27 13:54

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[profanity.validators.validate_is_profane]),
        ),
    ]
