# Generated by Django 2.1.5 on 2019-05-03 15:37

import blog.formatChecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=blog.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
