# Generated by Django 2.1.5 on 2019-05-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20190503_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
