# Generated by Django 2.1.5 on 2019-05-04 07:38

import blog.formatChecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=blog.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
