# Generated by Django 2.1.5 on 2019-05-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='post',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
