# Generated by Django 2.1.5 on 2019-05-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_auto_20190504_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
