# Generated by Django 2.1.5 on 2019-05-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_pic/'),
        ),
    ]
