# Generated by Django 2.1.5 on 2019-05-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_auto_20190508_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='post_pic/'),
        ),
    ]
