# Generated by Django 2.1.5 on 2019-06-21 13:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_auto_20190511_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('share_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Share')),
            ],
        ),
    ]
