# Generated by Django 2.1.5 on 2019-06-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_quoteshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteshare',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quote_pic/'),
        ),
    ]
