# Generated by Django 2.1.5 on 2019-06-21 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0054_quoteshare_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='quote_pic/')),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('share_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Share')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='quoteshare',
            name='share_post',
        ),
        migrations.RemoveField(
            model_name='quoteshare',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuoteShare',
        ),
    ]
