# Generated by Django 2.1.5 on 2019-06-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_auto_20190621_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='is_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='share',
            name='share_post',
            field=models.ManyToManyField(blank=True, related_name='_share_share_post_+', to='blog.Share'),
        ),
    ]
