# Generated by Django 2.1.5 on 2019-06-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_auto_20190621_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='share_post',
        ),
    ]
