# Generated by Django 2.1.5 on 2019-06-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_remove_share_share_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='share_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Share'),
        ),
    ]
