# Generated by Django 2.1.5 on 2019-06-23 11:02

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=160, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=140, validators=[profanity.validators.validate_is_profane]),
        ),
        migrations.AlterField(
            model_name='share',
            name='content',
            field=models.TextField(blank=True, max_length=140, null=True, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
