# Generated by Django 2.1.5 on 2019-07-26 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_auto_20190708_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(['mp3'])]),
        ),
    ]
