# Generated by Django 2.1.5 on 2019-08-05 04:32

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import profanity.validators


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0063_auto_20190726_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=140, validators=[profanity.validators.validate_is_profane])),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ManyToManyField(related_name='admin_users', to=settings.AUTH_USER_MODEL)),
                ('first_member', models.ManyToManyField(related_name='first_member', to=settings.AUTH_USER_MODEL)),
                ('group_members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
