# Generated by Django 2.1.5 on 2019-08-05 04:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0064_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='WebGroup',
        ),
    ]
