# Generated by Django 2.1.5 on 2019-08-05 05:01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('blog', '0065_auto_20190805_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webgroup',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='webgroup',
            name='first_member',
        ),
        migrations.RemoveField(
            model_name='webgroup',
            name='group_members',
        ),
        migrations.DeleteModel(
            name='WebGroup',
        ),
    ]
