# Generated by Django 2.1.5 on 2019-08-05 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0067_webgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webgroup',
            name='first_member',
        ),
        migrations.AddField(
            model_name='webgroup',
            name='first_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_member', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
