# Generated by Django 2.1.5 on 2019-08-06 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0069_auto_20190805_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='share_post',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.GroupPost'),
            preserve_default=False,
        ),
    ]
