# Generated by Django 2.1.5 on 2019-08-06 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0071_grouppost_seen_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='is_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='group_post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
