# Generated by Django 2.2.4 on 2019-09-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0075_auto_20190807_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='content',
            field=models.TextField(),
        ),
    ]
