# Generated by Django 2.2.4 on 2019-09-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0076_auto_20190925_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
