# Generated by Django 2.2.4 on 2020-01-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0078_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
