# Generated by Django 2.2.4 on 2020-01-09 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=70)),
                ('prod_details', models.TextField()),
                ('prod_price', models.CharField(max_length=7)),
                ('prod_location', models.CharField(max_length=7)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('like', models.ManyToManyField(related_name='liked_product', to=settings.AUTH_USER_MODEL)),
                ('saved', models.ManyToManyField(related_name='saved_product', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prod_pic/')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
    ]
