# Generated by Django 2.2.4 on 2020-01-12 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like',
        ),
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='liked_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_category',
            field=models.CharField(blank=True, choices=[('', 'Select Field'), ('Accommodation', 'Accommodation'), ('Sound Devices', 'Sound Devices'), ('Cell/Mobile/Wireless Phones', 'Cell/Mobile/Wireless Phones'), ('Books', 'Books'), ('Computers', 'Computers'), ('TVs', 'TVs'), ('Cosmetics', 'Cosmetics'), ('Miscellaneous', 'Miscellaneous')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
