# Generated by Django 2.2.4 on 2020-01-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200112_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_location',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price',
            field=models.CharField(max_length=25),
        ),
    ]
