# Generated by Django 2.2.4 on 2020-01-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200112_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='saved',
        ),
    ]
