# Generated by Django 2.2.4 on 2020-01-16 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_product_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='prod_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
