# Generated by Django 2.2.4 on 2020-01-16 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='prod_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
