# Generated by Django 2.2.4 on 2020-01-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200117_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='save',
            new_name='saved',
        ),
    ]
