# Generated by Django 2.1.7 on 2019-04-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follower',
        ),
    ]
