# Generated by Django 2.1.7 on 2019-04-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20190403_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follow',
            new_name='following',
        ),
    ]
