# Generated by Django 2.1.5 on 2019-05-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20190502_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='view_count',
            new_name='monetized_views',
        ),
        migrations.AddField(
            model_name='monetization',
            name='status',
            field=models.CharField(choices=[('Cleared', 'Cleared'), ('uncleared', 'Uncleared')], default='uncleared', max_length=10),
        ),
    ]
