# Generated by Django 2.1.5 on 2019-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20190502_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('gt', 'GT Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('first', 'First Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('access', 'Access Bank Plc')], default='gt', max_length=20),
        ),
    ]
