# Generated by Django 2.1.5 on 2019-05-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_monetization_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='monetization',
            name='account_num',
            field=models.PositiveIntegerField(default=1234567890),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('first', 'First Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('gt', 'GT Bank Plc'), ('access', 'Access Bank Plc')], default='gt', max_length=20),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='status',
            field=models.CharField(choices=[('uncleared', 'Uncleared'), ('Cleared', 'Cleared')], default='uncleared', max_length=10),
        ),
    ]
