# Generated by Django 2.1.5 on 2019-05-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20190502_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetization',
            name='account_num',
            field=models.IntegerField(default=1234567890),
        ),
    ]
