# Generated by Django 2.1.5 on 2019-05-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_auto_20190502_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('access', 'Access Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('gt', 'GT Bank Plc'), ('first', 'First Bank Plc')], default='gt', max_length=20),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='status',
            field=models.CharField(choices=[('uncleared', 'Uncleared'), ('Cleared', 'Cleared')], default='uncleared', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='monetized_views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
