# Generated by Django 2.1.5 on 2019-05-03 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_auto_20190502_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='monetization',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('polaris', 'Polaris Bank Plc'), ('first', 'First Bank Plc'), ('access', 'Access Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('gt', 'GT Bank Plc')], default='gt', max_length=20),
        ),
    ]
