# Generated by Django 2.1.5 on 2019-05-03 03:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_auto_20190503_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='monetization',
            name='transaction_ref',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('first', 'First Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('gt', 'GT Bank Plc'), ('access', 'Access Bank Plc')], default='gt', max_length=20),
        ),
    ]
