# Generated by Django 2.1.5 on 2019-05-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_auto_20190503_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='monetized_views',
        ),
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('gt', 'GT Bank Plc'), ('first', 'First Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('access', 'Access Bank Plc'), ('polaris', 'Polaris Bank Plc')], default='gt', max_length=20),
        ),
    ]
