# Generated by Django 2.1.5 on 2019-05-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_auto_20190503_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_monetized',
        ),
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('first', 'First Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('access', 'Access Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('gt', 'GT Bank Plc')], default='gt', max_length=20),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='status',
            field=models.CharField(choices=[('Cleared', 'Cleared'), ('uncleared', 'Uncleared')], default='uncleared', max_length=10),
        ),
    ]
