# Generated by Django 2.1.5 on 2019-05-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_auto_20190503_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetization',
            name='account_num',
            field=models.PositiveIntegerField(default=1234567890),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('polaris', 'Polaris Bank Plc'), ('first', 'First Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('gt', 'GT Bank Plc'), ('access', 'Access Bank Plc')], default='gt', max_length=20),
        ),
    ]
