# Generated by Django 2.1.5 on 2019-05-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_auto_20190503_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='monetization',
            name='account_name',
            field=models.CharField(default='Account Name', max_length=140),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('first', 'First Bank Plc'), ('gt', 'GT Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('access', 'Access Bank Plc')], default='gt', max_length=20),
        ),
    ]
