# Generated by Django 2.1.5 on 2019-05-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_auto_20190503_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetization',
            name='account_name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='account_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('first', 'First Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('gt', 'GT Bank Plc'), ('access', 'Access Bank Plc')], default='gt', max_length=20),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='status',
            field=models.CharField(choices=[('Cleared', 'Cleared'), ('uncleared', 'Uncleared')], default='uncleared', max_length=10),
        ),
    ]
