# Generated by Django 2.1.5 on 2019-05-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_auto_20190503_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('first', 'First Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('gt', 'GT Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('access', 'Access Bank Plc')], default='gt', max_length=20),
        ),
    ]
