# Generated by Django 2.1.5 on 2019-05-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0072_auto_20190504_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('zenith', 'Zenith Bank Plc'), ('gt', 'GT Bank Plc'), ('access', 'Access Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('first', 'First Bank Plc')], default='gt', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deleted_post_views',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
