# Generated by Django 2.1.5 on 2019-05-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_auto_20190504_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('gt', 'GT Bank Plc'), ('first', 'First Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('access', 'Access Bank Plc'), ('zenith', 'Zenith Bank Plc')], default='gt', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deleted_post_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
