# Generated by Django 2.1.5 on 2019-05-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_auto_20190504_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='monetized_views',
        ),
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('polaris', 'Polaris Bank Plc'), ('first', 'First Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('gt', 'GT Bank Plc'), ('access', 'Access Bank Plc')], default='gt', max_length=20),
        ),
    ]
