# Generated by Django 2.1.5 on 2019-05-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0075_auto_20190504_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monetized_views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('zenith', 'Zenith Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('gt', 'GT Bank Plc'), ('first', 'First Bank Plc'), ('access', 'Access Bank Plc')], default='gt', max_length=20),
        ),
    ]
