# Generated by Django 2.1.5 on 2019-05-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0076_auto_20190504_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('first', 'First Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('gt', 'GT Bank Plc'), ('access', 'Access Bank Plc')], default='gt', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='monetized_views',
            field=models.IntegerField(default=0),
        ),
    ]
