# Generated by Django 2.1.5 on 2019-05-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0077_auto_20190504_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='deleted_post_views',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='monetized_views',
        ),
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('zenith', 'Zenith Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('access', 'Access Bank Plc'), ('gt', 'GT Bank Plc'), ('first', 'First Bank Plc')], default='gt', max_length=20),
        ),
    ]
