# Generated by Django 2.1.5 on 2019-05-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0080_auto_20190504_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_monetized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('polaris', 'Polaris Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('first', 'First Bank Plc'), ('gt', 'GT Bank Plc'), ('access', 'Access Bank Plc')], default='gt', max_length=20),
        ),
    ]
