# Generated by Django 2.1.5 on 2019-05-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0087_auto_20190507_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('zenith', 'Zenith Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('first', 'First Bank Plc'), ('access', 'Access Bank Plc'), ('gt', 'GT Bank Plc')], default='gt', max_length=20),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='status',
            field=models.CharField(choices=[('uncleared', 'Uncleared'), ('Cleared', 'Cleared')], default='uncleared', max_length=10),
        ),
    ]
