# Generated by Django 2.1.5 on 2019-06-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0099_auto_20190613_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('access', 'Access Bank Plc'), ('gt', 'GT Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('first', 'First Bank Plc'), ('zenith', 'Zenith Bank Plc')], default='gt', max_length=20),
        ),
    ]
