# Generated by Django 2.1.5 on 2019-06-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0106_auto_20190616_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('polaris', 'Polaris Bank Plc'), ('gt', 'GT Bank Plc'), ('access', 'Access Bank Plc'), ('first', 'First Bank Plc'), ('zenith', 'Zenith Bank Plc')], default='gt', max_length=20),
        ),
    ]
