# Generated by Django 2.1.5 on 2019-06-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0110_auto_20190619_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('zenith', 'Zenith Bank Plc'), ('gt', 'GT Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('access', 'Access Bank Plc'), ('first', 'First Bank Plc')], default='gt', max_length=20),
        ),
    ]
