# Generated by Django 2.1.5 on 2019-06-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0115_auto_20190621_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('gt', 'GT Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('first', 'First Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('access', 'Access Bank Plc')], default='gt', max_length=20),
        ),
    ]
