# Generated by Django 2.1.5 on 2019-07-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0129_auto_20190706_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('gt', 'GT Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('first', 'First Bank Plc'), ('polaris', 'Polaris Bank Plc'), ('access', 'Access Bank Plc')], default='gt', max_length=20),
        ),
        migrations.AlterField(
            model_name='monetization',
            name='status',
            field=models.CharField(choices=[('Cleared', 'Cleared'), ('uncleared', 'Uncleared')], default='uncleared', max_length=10),
        ),
    ]
