# Generated by Django 2.1.5 on 2019-07-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0131_auto_20190706_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetization',
            name='bank',
            field=models.CharField(choices=[('polaris', 'Polaris Bank Plc'), ('zenith', 'Zenith Bank Plc'), ('gt', 'GT Bank Plc'), ('first', 'First Bank Plc'), ('access', 'Access Bank Plc')], default='gt', max_length=20),
        ),
    ]
