# Generated by Django 2.1.5 on 2019-07-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0137_auto_20190708_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='website_img')),
            ],
        ),
    ]
