# Generated by Django 2.1.5 on 2019-07-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0138_adminupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUpload',
        ),
    ]
