# Generated by Django 2.1.5 on 2019-07-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0141_auto_20190731_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='post',
            new_name='admin',
        ),
    ]
