# Generated by Django 2.1.5 on 2019-07-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0142_auto_20190731_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='AdminImages',
        ),
    ]
