# Generated by Django 2.1.5 on 2019-08-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0144_auto_20190731_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='website_img/'),
        ),
    ]
