# Generated by Django 2.1.5 on 2019-08-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0146_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('default', ''), ('male', 'Male'), ('female', 'Female')], default='default', max_length=20),
        ),
    ]
