# Generated by Django 2.1.5 on 2019-08-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0150_useremailrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useremailrequest',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
