# Generated by Django 2.2.4 on 2019-09-10 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=140)),
                ('job_description', models.TextField()),
                ('method_of_application', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_pic/')),
                ('field', models.CharField(choices=[('', 'Select Field'), ('admin', 'Administration/Secretarial'), ('agric', 'Agriculture/Agro-Allied'), ('arts/crafts/languages', 'Arts/Crafts/Languages'), ('Aviation/Airline', 'Aviation/Airline'), ('Banking', 'Banking'), ('Building and Construction', 'Building and Construction'), ('Catering / Confectionery', 'Catering / Confectionery'), ('Consultancy', 'Consultancy'), ('Customer Care', 'Customer Care'), ('Education / Teaching', 'Education / Teaching'), ('Engineering / Technical', 'Engineering / Technical'), ('Finance/Accouting/Audit', 'Finance/Accouting/Audit'), ('General', 'General'), ('Graduate Jobs', 'Graduate Jobs'), ('Hospitality/Hotel/Restaurant', 'Hospitality/Hotel/Restaurant'), ('HR', 'Human Resources'), ('Insurance', 'Insurance'), ('ICT', 'ICT/Computer'), ('Internships / Volunteering', 'Internships / Volunteering'), ('Janitorial Services', 'Janitorial Services'), ('Law / Legal', 'Law/Legal'), ('Logistics', 'Logistics'), ('Manutacturing', 'Manufacturing'), ('Media/ Advertising/ Branding', 'Media/ Advertising/ Branding'), ('Medical/Healthcare', 'Medical/Healthcare'), ('NGO/Non-Profit', 'NGO/Non-Profit'), ('Oil and Gas / Energy', 'Oil and Gas / Energy'), ('Pharmaceutical', 'Pharmaceutical'), ('Procurement / Store-keeping / Supply Chain', 'Procurement / Store-keeping / Supply Chain'), ('Project Management', 'Project Management'), ('Real Estate', 'Real Estate'), ('Research / Data Analysis', 'Research / Data Analysis'), ('Safety and Environment / HSE', 'Safety and Environment / HSE'), ('Sales / Marketing / Retail / Business Development', 'Sales / Marketing / Retail / Business Development'), ('Security Intelligence', 'Security Intelligence'), ('Transportation and Driving', 'Transportation and Driving'), ('Travel and Tours', 'Travel and Tours')], max_length=140)),
                ('education', models.CharField(choices=[('First School Leaving Certificate (FSLC)', 'First School Leaving Certificate (FSLC)'), ('Secondary School (SSCE)', 'Secondary School (SSCE)'), ('NCE', 'NCE'), ('OND', 'OND'), ('BA/BSc/HND', 'BA/BSc/HND'), ('MBA/MSc/MA', 'MBA/MSc/MA'), ('PhD/Fellowship', 'PhD/Fellowship'), ('Vocational', 'Vocational'), ('Others', 'Others')], default='Others', max_length=140)),
                ('industry', models.CharField(choices=[('', 'Select Industry'), ('Advertising / Branding / PR', 'Advertising / Branding / PR'), ('Agriculture / Agro-Allied', 'Agriculture / Agro-Allied'), ('any', 'Any'), ('Aviation / Airline', 'Aviation / Airline'), ('Banking / Financial Services', 'Banking / Financial Services'), ('Building / Construction', 'Building / Construction'), ('Consulting', 'Consulting'), ('Creative / Arts', 'Creative / Arts'), ('Education / Teaching', 'Education / Teaching'), ('Engineering / Technical', 'Engineering / Technical'), ('Food Services', 'Food Services'), ('General', 'General'), ('Government', 'Government'), ('Healthcare / Medical', 'Healthcare / Medical'), ('Hospitality', 'Hospitality'), ('ICT / Telecommunication', 'ICT / Telecommunication'), ('Insurance', 'Insurance'), ('Janitorial Services / Environment', 'Janitorial Services / Environment'), ('Law / Legal', 'Law / Legal'), ('Logistics and Transportation', 'Logistics and Transportation'), ('Manufacturing / Production / FMCG', 'Manufacturing / Production / FMCG'), ('Media / Radio / TV', 'Media / Radio / TV'), ('NGO / Non-Profit Associations', 'NGO / Non-Profit Associations'), ('Oil and Gas / Marine', 'Oil and Gas / Marine'), ('Online Sales / Marketing', 'Online Sales / Marketing'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Power / Energy', 'Power / Energy'), ('Professional / Social Associations', 'Professional / Social Associations'), ('Real Estate', 'Real Estate'), ('Religious', 'Religious'), ('Sales / Retail', 'Sales / Retail'), ('Security', 'Security'), ('Travel and Tours', 'Travel and Tours')], default='any', max_length=140)),
                ('video', models.FileField(blank=True, null=True, upload_to='job_vid/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
