# Generated by Django 2.2.4 on 2019-09-11 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20190910_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopening',
            name='video',
        ),
    ]
