# Generated by Django 2.2.4 on 2019-09-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobopening_send_cv_directly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='method_of_application',
            field=models.TextField(blank=True, null=True),
        ),
    ]
