# Generated by Django 2.2.4 on 2019-09-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20190911_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='experience',
            field=models.CharField(choices=[('1-4', '1-4 years'), ('5-10', '5-10 years'), ('11-35', '11-35 years')], default=-3, max_length=20),
            preserve_default=False,
        ),
    ]
