# Generated by Django 2.2.4 on 2019-09-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20190911_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='experience',
            field=models.CharField(choices=[('', 'Select Experience Required'), ('1-4', '1-4 years'), ('5-10', '5-10 years'), ('11-35', '11-35 years')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
