# Generated by Django 2.2.4 on 2019-09-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20190911_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='company_email',
            field=models.EmailField(default='lekan@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
