# Generated by Django 2.2.4 on 2019-09-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_jobopening_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Contract', 'Contract')], default='Contract', max_length=15),
            preserve_default=False,
        ),
    ]
