# Generated by Django 2.2.4 on 2019-09-14 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20190913_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopening',
            name='image',
        ),
    ]
