# Generated by Django 2.2.4 on 2019-09-14 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0015_remove_jobopening_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, validators=[profanity.validators.validate_is_profane])),
                ('image', models.ImageField(blank=True, null=True, upload_to='shared_pic/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_quote', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobOpening')),
                ('likes', models.ManyToManyField(blank=True, related_name='share_job_likes', to=settings.AUTH_USER_MODEL)),
                ('share_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.ShareJob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
