# Generated by Django 2.2.4 on 2019-09-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_requestjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='education',
            field=models.CharField(choices=[('First School Leaving Certificate (FSLC)', 'First School Leaving Certificate (FSLC)'), ('Secondary School (SSCE)', 'Secondary School (SSCE)'), ('NCE', 'NCE'), ('OND', 'OND'), ('BA/BSc/HND', 'BA/BSc/HND'), ('MBA/MSc/MA', 'MBA/MSc/MA'), ('PhD/Fellowship', 'PhD/Fellowship'), ('Vocational', 'Vocational'), ('Others', 'Others')], max_length=140),
        ),
    ]
