# Generated by Django 2.2.4 on 2019-09-22 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_auto_20190922_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestjob',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
