# Generated by Django 2.2.4 on 2019-09-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_requestjob_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Contract', 'Contract')], max_length=30),
        ),
    ]
