# Generated by Django 2.2.4 on 2019-09-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_auto_20190925_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopening',
            old_name='job_summary',
            new_name='company_description',
        ),
    ]
