# Generated by Django 2.2.4 on 2019-09-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_auto_20190927_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
