# Generated by Django 2.2.4 on 2019-10-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_auto_20190929_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharejob',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
